server:
  port: 8081

spring:
  application:
    name: ms-books-catalogue

# Eureka Client Settings
eureka:
  instance:
    preferIpAddress: true
    hostname: ms-books-catalogue
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

  elasticsearch:
    host: ${ELASTICSEARCH_HOST}
    credentials:
      user: ${ELASTICSEARCH_USER}
      password: ${ELASTIC_PWD}

  logging:
    level:
      tracer: TRACE