server:
  port: 8081

spring:
  application:
    name: ms-books-catalogue

  datasource:
    url: jdbc:h2:mem:catalogue-db
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql


# Eureka Client Settings
eureka:
  instance:
    preferIpAddress: true
    hostname: ms-books-catalogue
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}