spring:
  datasource:
    url: jdbc:h2:mem:catalogue-db
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      schema-locations: classpath:schema.sql
